version: 2.1
description: Validate the InSpec profile

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.3

jobs:
  inspec-check:
    executor: ruby
    environment:
      CHEF_LICENSE: accept-no-persist
    steps:
      - checkout
      - run:
          name: Install InSpec (free distribution) + cookstyle dep
          command: gem install --no-document inspec-core-bin:5.7.9 cookstyle
      - run:
          name: inspec check
          command: inspec check .

workflows:
  validate:
    jobs:
      - inspec-check
