version: 2.1
description: Validate the InSpec profile

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.3

jobs:
  inspec-check:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Install InSpec
          command: gem install --no-document inspec-core
      - run:
          name: inspec check
          command: inspec check .

workflows:
  validate:
    jobs:
      - inspec-check
