name: delivery

on: [push]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: install chef
      uses: actionshub/chef-install@master
    - name: cookstyle
      run: cookstyle -a
    - name: rake
      run: rake
